import { useState } from "react";
import { CheckCircle2, KeyRound, Loader2, LogOut, QrCode, RefreshCw } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { toast } from "sonner";
import type { WaBridgeStatus } from "@/lib/wa-bridge";

export function WaConnectionCard({ status, checking, onRefresh, onConnect, onPair, onDisconnect }: { status: WaBridgeStatus; checking: boolean; onRefresh: () => Promise<unknown>; onConnect: (fresh?: boolean) => Promise<unknown>; onPair: (phone: string) => Promise<unknown>; onDisconnect: (erase?: boolean) => Promise<unknown> }) {
  const [phone, setPhone] = useState(""); const [busy, setBusy] = useState(false); const [codeMode, setCodeMode] = useState(false);
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); try { await action(); toast.success(success); } catch (error) { toast.error("Não foi possível concluir", { description: (error as Error).message }); } finally { setBusy(false); } };
  return <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className={`grid size-11 place-items-center rounded-2xl ${status.connected ? "bg-emerald-100 text-emerald-600" : "bg-amber-100 text-amber-600"}`}>{checking || busy ? <Loader2 className="animate-spin" /> : status.connected ? <CheckCircle2 /> : <QrCode />}</span><div><h2 className="font-sora text-xl font-bold">{status.connected ? "WhatsApp conectado" : status.qr ? "Escaneie o QR" : "Conecte seu WhatsApp"}</h2><p className="mt-1 max-w-xl text-sm text-slate-500">{status.connected ? `Número ${status.phone ?? ""}. Os disparos e conversas usam esta sessão local.` : "A conexão fica neste computador. Não abre WhatsApp Web nem exige extensão."}</p></div></div><div className="flex gap-2"><button onClick={() => void run(onRefresh, "Status atualizado")} className="rounded-xl border px-3 py-2 text-sm font-bold"><RefreshCw className="mr-1 inline size-4" />Verificar</button>{status.connected && <button onClick={() => void run(() => onDisconnect(false), "WhatsApp desconectado")} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-700"><LogOut className="mr-1 inline size-4" />Desconectar</button>}</div></div>
    {!status.connected && <div className="mt-6"><div className="flex gap-2 border-b"><button onClick={() => setCodeMode(false)} className={`px-3 py-2 text-sm font-bold ${!codeMode ? "border-b-2 border-emerald-500 text-emerald-600" : "text-slate-500"}`}>QR code</button><button onClick={() => setCodeMode(true)} className={`px-3 py-2 text-sm font-bold ${codeMode ? "border-b-2 border-emerald-500 text-emerald-600" : "text-slate-500"}`}>Conectar por código</button></div>{!codeMode ? <div className="mt-5 text-center">{status.qr ? <div className="inline-block rounded-2xl border bg-white p-4"><QRCodeSVG value={status.qr} size={250} level="M" /></div> : <button disabled={busy} onClick={() => void run(() => onConnect(false), "Conexão iniciada. Aguarde o QR aparecer.")} className="rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">Gerar QR code</button>}<p className="mt-3 text-xs text-slate-500">No celular: WhatsApp → Aparelhos conectados → Conectar um aparelho.</p></div> : <div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-600">Informe seu número com DDD. O Mega Lead exibirá o código para digitar no WhatsApp do celular.</p><div className="mt-3 flex gap-2"><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="(21) 99999-9999" className="min-w-0 flex-1 rounded-xl border bg-white px-3 py-2.5"/><button disabled={busy || phone.replace(/\D/g, "").length < 10} onClick={() => void run(() => onPair(phone), "Código gerado")} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><KeyRound className="mr-1 inline size-4" />Gerar código</button></div>{status.pairingCode && <div className="mt-4 rounded-xl border border-emerald-200 bg-white p-4 text-center"><p className="text-xs font-bold uppercase text-emerald-700">Código de pareamento</p><p className="mt-2 font-mono text-3xl font-black tracking-[.2em]">{status.pairingCode.match(/.{1,4}/g)?.join("-")}</p><p className="mt-2 text-xs text-slate-500">No celular: Aparelhos conectados → Conectar com número de telefone.</p></div>}</div>}</div>}
  </section>;
}
