/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedConexoesRouteImport } from './routes/_authenticated/conexoes'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPrivacidadeRouteImport } from './routes/_authenticated/privacidade'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api/public/webhooks/meta'
import { Route as ApiPublicWebhooksVelaniRouteImport } from './routes/api/public/webhooks/velani'
import { Route as ApiPublicWorkersMessagesRouteImport } from './routes/api/public/workers/messages'
import { Route as ApiPublicWorkersRetentionRouteImport } from './routes/api/public/workers/retention'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConexoesRoute = AuthenticatedConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacidadeRoute =
  AuthenticatedPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksVelaniRoute = ApiPublicWebhooksVelaniRouteImport.update({
  id: '/api/public/webhooks/velani',
  path: '/api/public/webhooks/velani',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkersMessagesRoute =
  ApiPublicWorkersMessagesRouteImport.update({
    id: '/api/public/workers/messages',
    path: '/api/public/workers/messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkersRetentionRoute =
  ApiPublicWorkersRetentionRouteImport.update({
    id: '/api/public/workers/retention',
    path: '/api/public/workers/retention',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/velani': typeof ApiPublicWebhooksVelaniRoute
  '/api/public/workers/messages': typeof ApiPublicWorkersMessagesRoute
  '/api/public/workers/retention': typeof ApiPublicWorkersRetentionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/velani': typeof ApiPublicWebhooksVelaniRoute
  '/api/public/workers/messages': typeof ApiPublicWorkersMessagesRoute
  '/api/public/workers/retention': typeof ApiPublicWorkersRetentionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/conexoes': typeof AuthenticatedConexoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/privacidade': typeof AuthenticatedPrivacidadeRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/public/webhooks/velani': typeof ApiPublicWebhooksVelaniRoute
  '/api/public/workers/messages': typeof ApiPublicWorkersMessagesRoute
  '/api/public/workers/retention': typeof ApiPublicWorkersRetentionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/download'
    | '/politica-de-privacidade'
    | '/termos'
    | '/conexoes'
    | '/crm'
    | '/dashboard'
    | '/inbox'
    | '/leads'
    | '/mapa'
    | '/planos'
    | '/privacidade'
    | '/whatsapp'
    | '/api/public/health'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/velani'
    | '/api/public/workers/messages'
    | '/api/public/workers/retention'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/download'
    | '/politica-de-privacidade'
    | '/termos'
    | '/conexoes'
    | '/crm'
    | '/dashboard'
    | '/inbox'
    | '/leads'
    | '/mapa'
    | '/planos'
    | '/privacidade'
    | '/whatsapp'
    | '/api/public/health'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/velani'
    | '/api/public/workers/messages'
    | '/api/public/workers/retention'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/download'
    | '/politica-de-privacidade'
    | '/termos'
    | '/_authenticated/conexoes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/leads'
    | '/_authenticated/mapa'
    | '/_authenticated/planos'
    | '/_authenticated/privacidade'
    | '/_authenticated/whatsapp'
    | '/api/public/health'
    | '/api/public/webhooks/meta'
    | '/api/public/webhooks/velani'
    | '/api/public/workers/messages'
    | '/api/public/workers/retention'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
  ApiPublicWebhooksVelaniRoute: typeof ApiPublicWebhooksVelaniRoute
  ApiPublicWorkersMessagesRoute: typeof ApiPublicWorkersMessagesRoute
  ApiPublicWorkersRetentionRoute: typeof ApiPublicWorkersRetentionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conexoes': {
      id: '/_authenticated/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof AuthenticatedConexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacidade': {
      id: '/_authenticated/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof AuthenticatedPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/velani': {
      id: '/api/public/webhooks/velani'
      path: '/api/public/webhooks/velani'
      fullPath: '/api/public/webhooks/velani'
      preLoaderRoute: typeof ApiPublicWebhooksVelaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/messages': {
      id: '/api/public/workers/messages'
      path: '/api/public/workers/messages'
      fullPath: '/api/public/workers/messages'
      preLoaderRoute: typeof ApiPublicWorkersMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/retention': {
      id: '/api/public/workers/retention'
      path: '/api/public/workers/retention'
      fullPath: '/api/public/workers/retention'
      preLoaderRoute: typeof ApiPublicWorkersRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConexoesRoute: typeof AuthenticatedConexoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrivacidadeRoute: typeof AuthenticatedPrivacidadeRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConexoesRoute: AuthenticatedConexoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrivacidadeRoute: AuthenticatedPrivacidadeRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
  ApiPublicWebhooksVelaniRoute: ApiPublicWebhooksVelaniRoute,
  ApiPublicWorkersMessagesRoute: ApiPublicWorkersMessagesRoute,
  ApiPublicWorkersRetentionRoute: ApiPublicWorkersRetentionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
