// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
let refreshing: ReturnType<typeof supabase.auth.refreshSession> | null = null

export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data: initial } = await supabase.auth.getSession()
    let session = initial.session

    // A desktop window can stay open for days. Refresh the access token before
    // sending a server function, so the UI never looks authenticated while the
    // API rejects the old token in the background.
    if (session && (session.expires_at ?? 0) * 1000 < Date.now() + 60000) {
      if (!refreshing) refreshing = supabase.auth.refreshSession().finally(() => { refreshing = null })
      const { data, error } = await refreshing
      if (!error && data.session) {
        session = data.session
      } else if (error) {
        // A temporary network failure must not erase a valid saved session.
        throw new Error('Não foi possível renovar sua sessão. Verifique a conexão e entre novamente se necessário.')
      }
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
